/*
 * Course: CSC-1120
 * JavaFX III
 * Login
 * Name: Sean Jones
 * Last Updated: 09-16-25
 */
package week3;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

/**
 * A JavaFX program that shows multiple nodes using the same
 * handler method, nesting containers to create a more complex
 * layout, and adding spacing, alignment, and margins to improve
 * the appearance of the app
 */
public class Login extends Application {
    private final HBox top = new HBox();
    private final HBox middle = new HBox();
    private final HBox bottom = new HBox();
    private final VBox parent = new VBox();

    private final Label username = new Label("Username");
    private final TextField usernameField = new TextField();

    private final Label password = new Label("Password");
    private final PasswordField passwordField = new PasswordField();

    private final Button cancel = new Button("Cancel");
    private final Button ok = new Button("OK");

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {


        top.getChildren().addAll(username, usernameField);
        middle.getChildren().addAll(password, passwordField);
        bottom.getChildren().addAll(cancel, ok);
        parent.getChildren().addAll(top, middle, bottom);

        // pretty-fying
        final int spacing = 10;
        top.setAlignment(Pos.CENTER);
        middle.setAlignment(Pos.CENTER);
        top.setSpacing(spacing);
        middle.setSpacing(spacing);
        parent.setAlignment(Pos.CENTER);
        parent.setSpacing(spacing);
        bottom.setAlignment(Pos.CENTER_RIGHT);
        bottom.setSpacing(spacing);
        final int rightMargin = 20;
        HBox.setMargin(ok, new Insets(0, rightMargin, 0, 0));

        // event handling
        cancel.setOnAction(_ -> cancel()); // unused param can be _
        ok.setOnAction(e -> ok(e));
        usernameField.setOnAction(this::ok); // method reference identical
        passwordField.setOnAction(this::ok); // functionality as lamba above

        final int width = 300;
        final int height = 150;
        stage.setScene(new Scene(parent, width, height));
        stage.setTitle("Login");
        stage.show();
    }

    /**
     * Event handler without the optional Event parameter
     */
    private void cancel() {
        usernameField.setText("");
        passwordField.setText("");
        Platform.exit(); // ends JavaFX program
    }

    /**
     * Event handler with the optional Event parameter
     * @param e the ActionEvent generated by either a {@link Button} or
     *          {@link TextField}
     */
    private void ok(ActionEvent e) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Login Successful");
        alert.setHeaderText("You logged in!");
        alert.setContentText("Secure, aren't we?");
        alert.show();
    }
}
